### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by WenxiongLiao** [TimHuisman1703/surtree#1]
Will the author provide a python version in the future? Or do other friends have a version implemented using python?

**Comment by TimHuisman1703** [comment]
This repo is dedicated to my Bachelor thesis, and is no longer being maintained. However, the logic has been ported to STreeD, which is still being maintained by my thesis supervisor, and also features a Python implementation: https://github.com/AlgTUDelft/pystreed/tree/main
